'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import {
  type Chain, type Mode, type AppState, type Finding, type Agent,
  type AuditReport, type ScopeMessage, type ScopeButton,
  CHAINS, DEFAULT_AGENTS,
} from '@/lib/types';
import { createClient } from '@/lib/supabase/client';
import { PentagonLogo, PentagonMark } from '@/components/PentagonLogo';
import type { User } from '@supabase/supabase-js';



// ─── Simple syntax highlighting ───
function highlightSolidity(line: string): string {
  return line
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/(\/\/.*)$/gm, '<span class="syn-comment">$1</span>')
    .replace(/\b(pragma|solidity|contract|function|returns?|import|from|public|private|internal|external|view|pure|payable|modifier|event|emit|mapping|struct|enum|if|else|for|while|require|revert|assert|using|is|abstract|interface|library|override|virtual|memory|storage|calldata|constructor|msg|block|tx|address|uint256|uint|int|bool|string|bytes|bytes32)\b/g,
      '<span class="syn-keyword">$1</span>')
    .replace(/\b(true|false)\b/g, '<span class="syn-keyword">$1</span>')
    .replace(/\b(\d+)\b/g, '<span class="syn-number">$1</span>')
    .replace(/"([^"]*)"/g, '<span class="syn-string">"$1"</span>')
    .replace(/'([^']*)'/g, '<span class="syn-string">\'$1\'</span>');
}

// ─── Report markdown generator ───
function generateReportMarkdown(report: AuditReport, contractName: string): string {
  const criticals = report.findings.filter(f => f.severity === 'critical');
  const highs = report.findings.filter(f => f.severity === 'high');
  const mediums = report.findings.filter(f => f.severity === 'medium');
  const lows = report.findings.filter(f => f.severity === 'low');

  let md = `# Pentagonal Security Audit Report\n\n`;
  md += `| Field | Value |\n|-------|-------|\n`;
  md += `| Contract | ${contractName} |\n`;
  md += `| Chain | ${report.chain} |\n`;
  md += `| Date | ${new Date(report.timestamp).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} |\n`;
  md += `| Security Score | ${report.riskScore}/100 |\n`;
  md += `| Rules Applied | ${report.rulesApplied} |\n\n`;

  md += `---\n\n## Executive Summary\n\n${report.summary}\n\n`;

  if (report.methodology) {
    md += `## Methodology\n\n${report.methodology}\n\n`;
  }

  md += `## Findings Overview\n\n`;
  md += `| Severity | Count |\n|----------|-------|\n`;
  md += `| Critical | ${criticals.length} |\n`;
  md += `| High | ${highs.length} |\n`;
  md += `| Medium | ${mediums.length} |\n`;
  md += `| Low | ${lows.length} |\n`;
  md += `| **Total** | **${report.findings.length}** |\n\n`;

  // Code Segment Analysis
  if (report.codeSegments && report.codeSegments.length > 0) {
    md += `---\n\n## Code Segment Review\n\n`;
    for (let i = 0; i < report.codeSegments.length; i++) {
      const seg = report.codeSegments[i];
      const segFindings = report.findings.filter(f =>
        f.line && f.line >= seg.startLine && f.line <= seg.endLine
      );
      md += `### ${i + 1}. ${seg.title} (L${seg.startLine}–${seg.endLine}) — ${seg.risk.toUpperCase()}\n\n`;
      md += `${seg.summary}\n\n`;
      md += `\`\`\`solidity\n${seg.code}\n\`\`\`\n\n`;
      if (segFindings.length > 0) {
        md += `**Findings in this segment:**\n`;
        for (const f of segFindings) {
          md += `- [${f.severity.toUpperCase()}] ${f.title}${f.line ? ` (L${f.line})` : ''}\n`;
        }
        md += `\n`;
      }
    }
  }

  // Detailed Findings
  if (report.findings.length > 0) {
    md += `---\n\n## Detailed Findings\n\n`;
    for (let i = 0; i < report.findings.length; i++) {
      const f = report.findings[i];
      md += `### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title}\n\n`;
      md += `**Agent:** ${f.agent}`;
      if (f.line) md += ` | **Line:** ${f.line}`;
      md += `\n\n${f.description}\n\n`;
      if (f.recommendation) md += `> **Recommendation:** ${f.recommendation}\n\n`;
    }
  }

  // Agent Performance
  md += `---\n\n## Agent Performance\n\n`;
  md += `| Agent | Status | Findings |\n|-------|--------|----------|\n`;
  for (const ar of report.agentResults) {
    md += `| ${ar.agentName} | ${ar.findingCount > 0 ? '⚠ Findings' : '✓ Clear'} | ${ar.findingCount} |\n`;
  }
  md += `\n`;

  md += `---\n\n## Recommendation\n\n${report.recommendation}\n\n`;
  md += `---\n\n*Generated by Pentagonal — Smart Contract Forge · ${new Date(report.timestamp).toLocaleString()}*\n`;
  return md;
}

export default function Home() {
  // ─── Core State ───
  const [appState, setAppState] = useState<AppState>('landing');
  const [mode, setMode] = useState<Mode>('create');
  const [chain, setChain] = useState<Chain>(CHAINS[0]);
  const [showChainDropdown, setShowChainDropdown] = useState(false);
  const [learningOn, setLearningOn] = useState(true);
  const [prompt, setPrompt] = useState('');
  const [currentPrompt, setCurrentPrompt] = useState('');
  const [rulesCount, setRulesCount] = useState(0);
  const [rulesList, setRulesList] = useState<string[]>([]);
  const [showRules, setShowRules] = useState(false);

  // ─── Auth State ───
  const [user, setUser] = useState<User | null>(null);
  const [showUserMenu, setShowUserMenu] = useState(false);
  const supabase = createClient();

  // ─── Scoping State ───
  const [scopeMessages, setScopeMessages] = useState<ScopeMessage[]>([]);
  const [isScopeLoading, setIsScopeLoading] = useState(false);
  const scopeEndRef = useRef<HTMLDivElement>(null);

  // ─── Code State ───
  const [code, setCode] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const [fileName, setFileName] = useState('Contract.sol');

  // ─── Hover Explanation ───
  const [hoveredLine, setHoveredLine] = useState<number | null>(null);
  const [tooltip, setTooltip] = useState<{ title: string; explanation: string; line: number } | null>(null);
  const tooltipCache = useRef<Map<string, { title: string; explanation: string }>>(new Map());

  // ─── Token Info ───
  interface TokenInfo {
    found: boolean;
    name?: string;
    symbol?: string;
    priceUsd?: string;
    priceChange24h?: number;
    volume24h?: number;
    txns24h?: number;
    buys24h?: number;
    sells24h?: number;
    liquidity?: number;
    marketCap?: number;
    pairCount?: number;
    dexName?: string;
    imageUrl?: string;
    url?: string;
    message?: string;
  }
  const [tokenInfo, setTokenInfo] = useState<TokenInfo | null>(null);

  // ─── Audit State ───
  const [agents, setAgents] = useState<Agent[]>(DEFAULT_AGENTS.map(a => ({ ...a })));
  const [findings, setFindings] = useState<Finding[]>([]);
  const [isAuditing, setIsAuditing] = useState(false);
  const [auditProgress, setAuditProgress] = useState(0);
  const [report, setReport] = useState<AuditReport | null>(null);
  const [showReport, setShowReport] = useState(false);

  // ─── Address Fetch State ───
  const [addressInput, setAddressInput] = useState('');
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState('');
  const [isDetectingChain, setIsDetectingChain] = useState(false);
  const detectTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  // ─── Q&A State ───
  const [qaAnswer, setQaAnswer] = useState('');
  const [qaLoading, setQaLoading] = useState(false);

  // ─── Refs ───
  const codeBodyRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const chainDropdownRef = useRef<HTMLDivElement>(null);

  // Auto-scroll code body during streaming
  useEffect(() => {
    if (isStreaming && codeBodyRef.current) {
      codeBodyRef.current.scrollTop = codeBodyRef.current.scrollHeight;
    }
  }, [code, isStreaming]);

  // Close chain dropdown on click outside
  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (chainDropdownRef.current && !chainDropdownRef.current.contains(e.target as Node)) {
        setShowChainDropdown(false);
      }
    }
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, []);

  // Fetch rules count on mount
  useEffect(() => {
    fetch('/api/rules-count').then(r => r.json()).then(d => {
      setRulesCount(d.count || 0);
      setRulesList(d.rules || []);
    }).catch(() => {});
  }, []);

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = textareaRef.current.scrollHeight + 'px';
    }
  }, [prompt]);

  // Auth state listener
  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }) => setUser(user));
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user ?? null);
    });
    return () => subscription.unsubscribe();
  }, [supabase.auth]);

  // Auto-scroll scope messages
  useEffect(() => {
    if (scopeEndRef.current) {
      scopeEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [scopeMessages]);

  // ─── Start Scoping ───
  const startScoping = useCallback(async (initialPrompt: string) => {
    setAppState('scoping');
    setCurrentPrompt(initialPrompt);
    setIsScopeLoading(true);
    setScopeMessages([{ role: 'user', content: initialPrompt }]);
    setPrompt('');

    try {
      const res = await fetch('/api/scope', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ initialPrompt, chain: chain.id }),
      });
      const data = await res.json();

      const aiMsg: ScopeMessage = {
        role: 'assistant',
        content: data.question || data.summary || '',
        buttons: data.buttons,
        multiSelect: data.multiSelect,
        inputNeeded: data.inputNeeded,
        isConfirmation: data.confirmed,
        generationPrompt: data.generationPrompt,
      };
      setScopeMessages(prev => [...prev, aiMsg]);
    } catch {
      setScopeMessages(prev => [...prev, { role: 'assistant', content: 'Something went wrong. Please try again.' }]);
    }
    setIsScopeLoading(false);
  }, [chain]);

  // ─── Send scope response (typed or button) ───
  const sendScopeResponse = useCallback(async (userResponse: string) => {
    const newUserMsg: ScopeMessage = { role: 'user', content: userResponse };
    const updatedMessages = [...scopeMessages, newUserMsg];
    setScopeMessages(updatedMessages);
    setIsScopeLoading(true);
    setPrompt('');

    // Build history for API
    const history = updatedMessages.map(m => ({
      role: m.role,
      content: m.role === 'assistant' && m.buttons
        ? JSON.stringify({ question: m.content, buttons: m.buttons, multiSelect: m.multiSelect })
        : m.content,
    }));

    try {
      const res = await fetch('/api/scope', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ history, chain: chain.id }),
      });
      const data = await res.json();

      const aiMsg: ScopeMessage = {
        role: 'assistant',
        content: data.question || data.summary || '',
        buttons: data.buttons,
        multiSelect: data.multiSelect,
        inputNeeded: data.inputNeeded,
        isConfirmation: data.confirmed,
        generationPrompt: data.generationPrompt,
      };
      setScopeMessages(prev => [...prev, aiMsg]);
    } catch {
      setScopeMessages(prev => [...prev, { role: 'assistant', content: 'Something went wrong. Please try again.' }]);
    }
    setIsScopeLoading(false);
  }, [scopeMessages, chain]);

  // ─── Handle button click in scoping ───
  const handleScopeButton = useCallback((button: ScopeButton, msgIndex: number, multiSelect?: boolean) => {
    if (multiSelect) {
      // Toggle selection
      setScopeMessages(prev => prev.map((m, i) => {
        if (i !== msgIndex || !m.buttons) return m;
        return {
          ...m,
          buttons: m.buttons.map(b =>
            b.value === button.value ? { ...b, selected: !b.selected } : b
          ),
        };
      }));
    } else {
      // Single select → send immediately
      sendScopeResponse(button.label);
    }
  }, [sendScopeResponse]);

  // ─── Confirm multi-select ───
  const confirmMultiSelect = useCallback((msgIndex: number) => {
    const msg = scopeMessages[msgIndex];
    if (!msg?.buttons) return;
    const selected = msg.buttons.filter(b => b.selected).map(b => b.label);
    sendScopeResponse(selected.length > 0 ? selected.join(', ') : 'None');
  }, [scopeMessages, sendScopeResponse]);

  // ─── Generate from scope (after confirmation) ───
  const generateFromScope = useCallback(async (genPrompt: string) => {
    setCode('');
    setFindings([]);
    setAgents(DEFAULT_AGENTS.map(a => ({ ...a })));
    setReport(null);
    setShowReport(false);
    setIsStreaming(true);
    setAppState('streaming');
    setQaAnswer('');
    setScopeMessages([]);

    const nameMatch = genPrompt.match(/called?\s+(\w+)/i);
    const ext = chain.type === 'solana' ? '.rs' : '.sol';
    setFileName(nameMatch ? nameMatch[1] + ext : 'Contract' + ext);

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: genPrompt, chain: chain.id, learningOn }),
      });

      const reader = res.body?.getReader();
      if (!reader) throw new Error('No response body');

      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6));
              if (data.text) {
                setCode((prev) => prev + data.text);
              } else if (data.done) {
                setIsStreaming(false);
                setAppState('complete');
              } else if (data.error) {
                setIsStreaming(false);
                setAppState('complete');
              }
            } catch { /* skip */ }
          }
        }
      }
    } catch {
      setIsStreaming(false);
      setAppState('complete');
    }
  }, [chain, learningOn]);

  // ─── Generate Contract (direct, for Q&A refinements) ───
  const handleGenerate = useCallback(async () => {
    if (!prompt.trim() || isStreaming) return;

    const currentInput = prompt;
    setCurrentPrompt(currentInput);
    setCode('');
    setFindings([]);
    setAgents(DEFAULT_AGENTS.map(a => ({ ...a })));
    setReport(null);
    setShowReport(false);
    setIsStreaming(true);
    setAppState('streaming');
    setQaAnswer('');

    const nameMatch = currentInput.match(/called?\s+(\w+)/i);
    const ext = chain.type === 'solana' ? '.rs' : '.sol';
    setFileName(nameMatch ? nameMatch[1] + ext : 'Contract' + ext);
    setPrompt('');

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: currentInput, chain: chain.id, learningOn }),
      });

      const reader = res.body?.getReader();
      if (!reader) throw new Error('No response body');

      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6));
              if (data.text) {
                setCode((prev) => prev + data.text);
              } else if (data.done) {
                setIsStreaming(false);
                setAppState('complete');
              } else if (data.error) {
                setIsStreaming(false);
                setAppState('complete');
              }
            } catch { /* skip */ }
          }
        }
      }
    } catch {
      setIsStreaming(false);
      setAppState('complete');
    }
  }, [prompt, chain, learningOn, isStreaming]);

  // ─── Fetch on-chain contract ───
  const handleFetchContract = useCallback(async () => {
    if (!addressInput.trim() || isFetching) return;

    setIsFetching(true);
    setFetchError('');

    try {
      const res = await fetch('/api/fetch-contract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ address: addressInput.trim(), chainId: chain.id }),
      });

      const data = await res.json();

      if (!res.ok) {
        setFetchError(data.error || 'Failed to fetch contract');
        setIsFetching(false);
        return;
      }

      if (!data.code) {
        setFetchError(data.message || 'No source code available');
        setIsFetching(false);
        return;
      }

      setCode(data.code);
      setFileName(data.name + '.sol');
      setCurrentPrompt(`On-chain audit: ${data.name} (${addressInput.trim()})`);
      setIsFetching(false);

      // Fetch token market data from DexScreener
      fetch('/api/token-info', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ address: addressInput.trim(), chainId: chain.id }),
      })
        .then(r => r.json())
        .then(info => setTokenInfo(info))
        .catch(() => setTokenInfo(null));

      // Auto-start audit
      startAudit(data.code);
    } catch {
      setFetchError('Network error fetching contract');
      setIsFetching(false);
    }
  }, [addressInput, chain, isFetching]);

  // ─── Run step-by-step audit ───
  const startAudit = useCallback(async (codeToAudit?: string) => {
    const auditCode = codeToAudit || code;
    if (!auditCode.trim() || isAuditing) return;

    setIsAuditing(true);
    setAppState('auditing');
    setFindings([]);
    setReport(null);
    setShowReport(false);
    setAuditProgress(0);
    setQaAnswer('');

    // Reset agents to queued
    setAgents(DEFAULT_AGENTS.map(a => ({ ...a, status: 'queued' as const, findingCount: 0, findings: [] })));

    try {
      const res = await fetch('/api/audit-agent', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: auditCode, chain: chain.id, learningOn }),
      });

      if (!res.ok) {
        const errData = await res.json().catch(() => ({ error: 'Unknown error' }));
        console.error('Audit agent error:', errData);
        throw new Error(errData.error || `Server returned ${res.status}`);
      }

      const reader = res.body?.getReader();
      if (!reader) throw new Error('No response body');

      const decoder = new TextDecoder();
      let buffer = '';
      let completedCount = 0;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6));

              if (data.type === 'agent-start') {
                setAgents(prev => prev.map(a =>
                  a.id === data.agentId ? { ...a, status: 'scanning' as const } : a
                ));
              }

              if (data.type === 'agent-complete') {
                completedCount++;
                setAuditProgress(completedCount);

                const agentFindings: Finding[] = (data.findings || []).map((f: Finding, i: number) => ({
                  ...f,
                  id: `${data.agentId}-${i}`,
                }));

                setAgents(prev => prev.map(a =>
                  a.id === data.agentId ? {
                    ...a,
                    status: data.findingCount > 0
                      ? (agentFindings.some(f => f.severity === 'critical') ? 'critical' as const : 'finding' as const)
                      : 'clear' as const,
                    findingCount: data.findingCount,
                    findings: agentFindings,
                  } : a
                ));

                setFindings(prev => [...prev, ...agentFindings]);
              }

              if (data.type === 'agent-error') {
                completedCount++;
                setAuditProgress(completedCount);
                setAgents(prev => prev.map(a =>
                  a.id === data.agentId ? { ...a, status: 'clear' as const } : a
                ));
              }

              if (data.type === 'audit-complete') {
                const reportData: AuditReport = {
                  ...data.report,
                  contractName: tokenInfo?.name ? `${tokenInfo.name} (${tokenInfo.symbol})` : fileName,
                };
                setReport(reportData);
                setIsAuditing(false);
                setAppState('audit-complete');
              }
            } catch { /* skip */ }
          }
        }
      }
    } catch {
      setIsAuditing(false);
      setAppState('audit-complete');
    }
  }, [code, chain, learningOn, isAuditing, fileName]);

  // ─── Ask about code ───
  const handleAsk = useCallback(async () => {
    if (!prompt.trim() || !code || qaLoading) return;

    setQaLoading(true);
    setQaAnswer('');
    const question = prompt;
    setPrompt('');

    try {
      const res = await fetch('/api/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code, question }),
      });
      const data = await res.json();
      setQaAnswer(data.answer || 'No answer available.');
    } catch {
      setQaAnswer('Failed to get answer.');
    }
    setQaLoading(false);
  }, [prompt, code, qaLoading]);

  // ─── Handle Submit ───
  const handleSubmit = useCallback(() => {
    if (appState === 'scoping') {
      if (prompt.trim()) sendScopeResponse(prompt);
      return;
    }
    if (mode === 'create') {
      if (appState === 'landing') {
        startScoping(prompt);
      } else {
        handleGenerate();
      }
    } else {
      if (prompt.trim() && code) {
        handleAsk();
      } else if (code) {
        startAudit();
      }
    }
  }, [appState, mode, prompt, code, handleGenerate, handleAsk, startAudit, startScoping, sendScopeResponse]);

  // ─── Hover explanation ───
  const handleLineHover = useCallback(async (lineNum: number) => {
    if (isStreaming || !code) return;
    setHoveredLine(lineNum);

    const cacheKey = `${lineNum}-${lineNum + 4}`;
    const cached = tooltipCache.current.get(cacheKey);
    if (cached) { setTooltip({ ...cached, line: lineNum }); return; }

    try {
      const res = await fetch('/api/explain', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code, startLine: lineNum, endLine: Math.min(lineNum + 4, code.split('\n').length) }),
      });
      const data = await res.json();
      if (data.title) {
        tooltipCache.current.set(cacheKey, data);
        setTooltip({ ...data, line: lineNum });
      }
    } catch { /* quiet */ }
  }, [code, isStreaming]);

  // ─── Auto-fix ───
  const handleFix = useCallback(async (finding: Finding) => {
    try {
      const res = await fetch('/api/fix', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code, finding: { title: finding.title, description: finding.description } }),
      });
      const data = await res.json();
      if (data.code) {
        setCode(data.code);
        setFindings(prev => prev.map(f => f.id === finding.id ? { ...f, fixed: true } : f));
      }
    } catch { /* quiet */ }
  }, [code]);

  // ─── Download report ───
  const handleDownloadReport = useCallback(() => {
    if (!report) return;
    const md = generateReportMarkdown(report, fileName);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName.replace(/\.\w+$/, '')}-audit-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [report, fileName]);

  // ─── Key handler ───
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      if (mode === 'audit' && appState === 'landing' && addressInput.trim()) {
        handleFetchContract();
      } else if (appState === 'scoping' && prompt.trim()) {
        sendScopeResponse(prompt);
      } else {
        handleSubmit();
      }
    }
  };

  // ─── Render helpers ───
  const codeLines = code.split('\n');
  const isActive = appState !== 'landing';
  const isScopingView = appState === 'scoping';
  const isAuditView = appState === 'auditing' || appState === 'audit-complete';
  const progressPercent = Math.round((auditProgress / DEFAULT_AGENTS.length) * 100);

  return (
    <>
      {/* ─── Header ─── */}
      <header className="header">
        <div className="header-logo" onClick={() => {
          setAppState('landing');
          setCode('');
          setFindings([]);
          setReport(null);
          setShowReport(false);
          setCurrentPrompt('');
          setAddressInput('');
          setFetchError('');
          setScopeMessages([]);
          setAgents(DEFAULT_AGENTS.map(a => ({ ...a })));
        }} style={{ cursor: 'pointer' }}>
          <PentagonMark size={24} />
          Pentagonal
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          {rulesCount > 0 && (
            <div style={{ position: 'relative' }}>
              <button className="rules-counter" onClick={() => setShowRules(!showRules)}>
                {rulesCount} rules learned
              </button>
              {showRules && (
                <div className="rules-dropdown">
                  <div style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#6366f1', marginBottom: '8px' }}>Learned Rules</div>
                  <div className="rules-list">
                    {rulesList.map((rule, i) => (
                      <div key={i} className="rules-item">{rule}</div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
          <div className="learning-toggle" onClick={() => setLearningOn(!learningOn)}>
            <span>Learning</span>
            <div className={`toggle-pill ${learningOn ? 'on' : ''}`} />
          </div>
          {user && (
            <div style={{ position: 'relative' }}>
              <button className="user-avatar-btn" onClick={() => setShowUserMenu(!showUserMenu)}>
                {user.user_metadata?.avatar_url ? (
                  <img src={user.user_metadata.avatar_url} alt="" referrerPolicy="no-referrer" />
                ) : (
                  (user.email?.[0] || 'U').toUpperCase()
                )}
              </button>
              {showUserMenu && (
                <div className="user-menu">
                  <div className="user-menu-email">{user.email}</div>
                  <button className="user-menu-item danger" onClick={async () => {
                    await supabase.auth.signOut();
                    window.location.href = '/login';
                  }}>
                    Sign Out
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      </header>

      {/* ─── Main ─── */}
      <main className="main">
        <div className="content">

          {/* ═══════════════════════════════════════ */}
          {/* ─── LANDING STATE ─── */}
          {/* ═══════════════════════════════════════ */}
          {!isActive && (
            <div className="landing">
              <h1 className="hero-text">
                {mode === 'create' ? 'What would you like to build?' : 'What would you like to audit?'}
              </h1>

              <div className="prompt-container">
                <div className="prompt-box">
                  {/* Audit mode: address input */}
                  {mode === 'audit' ? (
                    <div style={{ padding: '16px 20px' }}>
                      <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                        <input
                          type="text"
                          className="address-input"
                          placeholder="Paste contract address (0x...) or paste code below"
                          value={addressInput}
                          onChange={(e) => {
                            const val = e.target.value.trim();
                            setAddressInput(e.target.value);
                            setFetchError('');

                            // Auto-detect chain when a valid address is pasted
                            if (detectTimeout.current) clearTimeout(detectTimeout.current);

                            // Solana: base58, 32-44 chars, no 0x prefix
                            if (val.length >= 32 && val.length <= 44 && !val.startsWith('0x') && /^[A-HJ-NP-Za-km-z1-9]+$/.test(val)) {
                              const solChain = CHAINS.find(c => c.id === 'solana');
                              if (solChain) setChain(solChain);
                              return;
                            }

                            // EVM: 0x + 40 hex chars — detect chain via DexScreener
                            if (/^0x[a-fA-F0-9]{40}$/.test(val)) {
                              setIsDetectingChain(true);
                              detectTimeout.current = setTimeout(async () => {
                                try {
                                  const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${val}`);
                                  const data = await res.json();
                                  const pairs = data?.pairs || [];
                                  if (pairs.length > 0) {
                                    // Find the chain with most liquidity
                                    const chainLiq: Record<string, number> = {};
                                    for (const p of pairs) {
                                      chainLiq[p.chainId] = (chainLiq[p.chainId] || 0) + (p.liquidity?.usd || 0);
                                    }
                                    const topChain = Object.entries(chainLiq).sort((a, b) => b[1] - a[1])[0]?.[0];
                                    if (topChain) {
                                      const match = CHAINS.find(c => c.id === topChain);
                                      if (match) setChain(match);
                                    }
                                  }
                                } catch { /* detection failed silently */ }
                                setIsDetectingChain(false);
                              }, 300);
                            }
                          }}
                          onKeyDown={(e) => { if (e.key === 'Enter') handleFetchContract(); }}
                          spellCheck={false}
                        />
                        <button
                          className="submit-btn"
                          onClick={handleFetchContract}
                          disabled={!addressInput.trim() || isFetching || isDetectingChain}
                          style={{ whiteSpace: 'nowrap' }}
                        >
                          {isDetectingChain ? 'Detecting...' : isFetching ? '...' : 'Fetch →'}
                        </button>
                      </div>
                      {fetchError && (
                        <div style={{ color: '#ef4444', fontSize: '13px', marginTop: '8px' }}>{fetchError}</div>
                      )}
                      <div style={{ borderTop: '1px solid #e2e8f0', margin: '12px 0', position: 'relative' }}>
                        <span style={{ position: 'absolute', top: '-10px', left: '50%', transform: 'translateX(-50%)', background: 'white', padding: '0 12px', fontSize: '12px', color: '#94a3b8' }}>or paste code</span>
                      </div>
                      <textarea
                        className="prompt-textarea"
                        placeholder="Paste smart contract code here..."
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        rows={4}
                        style={{ minHeight: '80px', fontFamily: 'var(--font-mono)', fontSize: '13px' }}
                      />
                    </div>
                  ) : (
                    <textarea
                      ref={textareaRef}
                      className="prompt-textarea"
                      placeholder="Describe your smart contract..."
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      onKeyDown={handleKeyDown}
                      rows={3}
                    />
                  )}

                  <div className="prompt-controls">
                    <div className="prompt-tabs">
                      <button
                        className={`prompt-tab ${mode === 'create' ? 'active' : ''}`}
                        onClick={() => setMode('create')}
                      >
                        ⚡ Create
                      </button>
                      <button
                        className={`prompt-tab ${mode === 'audit' ? 'active' : ''}`}
                        onClick={() => setMode('audit')}
                      >
                        🔍 Audit
                      </button>
                      <div ref={chainDropdownRef} style={{ position: 'relative' }}>
                        <button
                          className="chain-selector"
                          onClick={() => setShowChainDropdown(!showChainDropdown)}
                        >
                          <span>{chain.icon}</span>
                          <span>{chain.name}</span>
                          <span style={{ fontSize: '10px' }}>▾</span>
                        </button>
                        {showChainDropdown && (
                          <div className="chain-dropdown">
                            {CHAINS.map((c) => (
                              <button
                                key={c.id}
                                className={`chain-option ${c.id === chain.id ? 'selected' : ''}`}
                                onClick={() => { setChain(c); setShowChainDropdown(false); }}
                              >
                                <span>{c.icon}</span>
                                <span>{c.name}</span>
                                <span style={{ fontSize: '11px', color: '#94a3b8' }}>
                                  {c.type === 'solana' ? 'Rust' : 'Solidity'}
                                </span>
                              </button>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="prompt-right">
                      {mode === 'audit' && prompt.trim() ? (
                        <button
                          className="submit-btn"
                          onClick={() => {
                            setCode(prompt);
                            setCurrentPrompt('Manual code audit');
                            setFileName('Contract.sol');
                            setPrompt('');
                            startAudit(prompt);
                          }}
                        >
                          Audit Code →
                        </button>
                      ) : mode === 'create' ? (
                        <button
                          className="submit-btn"
                          onClick={handleSubmit}
                          disabled={!prompt.trim()}
                        >
                          Generate →
                        </button>
                      ) : null}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ═══════════════════════════════════════ */}
          {/* ─── SCOPING CONVERSATION ─── */}
          {/* ═══════════════════════════════════════ */}
          {isScopingView && (
            <div className="session">
              <div className="scope-thread">
                {scopeMessages.map((msg, idx) => (
                  <div key={idx} className={`scope-msg ${msg.role}`}>
                    {msg.role === 'assistant' && (
                      <div className="scope-avatar">⬠</div>
                    )}
                    <div className="scope-bubble">
                      {msg.isConfirmation ? (
                        <div className="scope-confirmation">
                          <div className="scope-confirm-label">Scope Confirmed</div>
                          <div style={{ whiteSpace: 'pre-wrap', fontSize: '14px', lineHeight: '1.7' }}>{msg.content}</div>
                          <button className="submit-btn" style={{ marginTop: '16px', width: '100%' }}
                            onClick={() => msg.generationPrompt && generateFromScope(msg.generationPrompt)}>
                            Generate Contract →
                          </button>
                        </div>
                      ) : (
                        <>
                          <div style={{ whiteSpace: 'pre-wrap' }}>{msg.content}</div>
                          {msg.buttons && (
                            <div className="scope-buttons">
                              {msg.buttons.map((btn, bi) => (
                                <button key={bi}
                                  className={`scope-btn ${btn.selected ? 'selected' : ''}`}
                                  onClick={() => handleScopeButton(btn, idx, msg.multiSelect)}>
                                  {btn.label}
                                </button>
                              ))}
                              {msg.multiSelect && (
                                <button className="scope-btn confirm"
                                  onClick={() => confirmMultiSelect(idx)}>
                                  Confirm ✓
                                </button>
                              )}
                            </div>
                          )}
                        </>
                      )}
                    </div>
                  </div>
                ))}
                {isScopeLoading && (
                  <div className="scope-msg assistant">
                    <div className="scope-avatar">⬠</div>
                    <div className="scope-bubble">
                      <span className="scope-typing">Thinking<span className="scope-dots">...</span></span>
                    </div>
                  </div>
                )}
                <div ref={scopeEndRef} />
              </div>
              <div style={{ height: '120px' }} />
            </div>
          )}

          {/* ═══════════════════════════════════════ */}
          {/* ─── CREATE SESSION ─── */}
          {/* ═══════════════════════════════════════ */}
          {isActive && !isAuditView && !isScopingView && (
            <div className="session">
              <div className="user-prompt-card">
                <div className="user-prompt-label">CREATE</div>
                {currentPrompt}
              </div>

              {code && (
                <div className="code-container">
                  <div className="code-header">
                    <input
                      type="text"
                      className="code-filename"
                      value={fileName}
                      onChange={(e) => setFileName(e.target.value)}
                      spellCheck={false}
                    />
                    <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                      {isStreaming && (
                        <span className="code-status">
                          <span className="code-status-dot" />
                          Generating...
                        </span>
                      )}
                      {!isStreaming && (
                        <>
                          <button className="code-action-btn" title="Copy code"
                            onClick={() => { navigator.clipboard.writeText(code); }}>
                            ⎘
                          </button>
                          <button className="code-action-btn" title="Download file"
                            onClick={() => {
                              const blob = new Blob([code], { type: 'text/plain' });
                              const url = URL.createObjectURL(blob);
                              const a = document.createElement('a');
                              a.href = url; a.download = fileName; a.click();
                              URL.revokeObjectURL(url);
                            }}>
                            ↓
                          </button>
                          <button className="code-action-btn" title="Audit this contract"
                            style={{ color: '#6366f1', fontWeight: 600, fontSize: '12px', width: 'auto', padding: '0 10px' }}
                            onClick={() => startAudit()}>
                            Audit →
                          </button>
                        </>
                      )}
                    </div>
                  </div>
                  <div className="code-body" ref={codeBodyRef}>
                    {codeLines.map((line, i) => (
                      <div
                        key={i}
                        className="code-line"
                        onMouseEnter={() => !isStreaming && handleLineHover(i + 1)}
                        onMouseLeave={() => { setHoveredLine(null); setTooltip(null); }}
                        style={{ position: 'relative' }}
                      >
                        <span className="line-number">{i + 1}</span>
                        <span className="line-content" dangerouslySetInnerHTML={{ __html: highlightSolidity(line) || '&nbsp;' }} />
                        {tooltip && tooltip.line === i + 1 && hoveredLine === i + 1 && (
                          <div className="code-tooltip">
                            <div className="code-tooltip-title">{tooltip.title}</div>
                            <div>{tooltip.explanation}</div>
                          </div>
                        )}
                      </div>
                    ))}
                    {isStreaming && <span className="cursor-blink" />}
                  </div>
                </div>
              )}

              {qaAnswer && (
                <div className="user-prompt-card" style={{ borderLeft: '3px solid #6366f1' }}>
                  <div className="user-prompt-label">ANSWER</div>
                  <div style={{ whiteSpace: 'pre-wrap', fontSize: '14px', lineHeight: '1.6' }}>{qaAnswer}</div>
                </div>
              )}

              <div style={{ height: '120px' }} />
            </div>
          )}

          {/* ═══════════════════════════════════════ */}
          {/* ─── AUDIT PAGE ─── */}
          {/* ═══════════════════════════════════════ */}
          {isAuditView && (
            <div className="audit-page">
              {/* Audit header bar */}
              <div className="audit-page-header">
                <div>
                  <div className="audit-label">SECURITY AUDIT</div>
                  <div className="audit-page-title">
                    {tokenInfo?.found ? `${tokenInfo.name} (${tokenInfo.symbol})` : fileName}
                  </div>
                  <div style={{ fontSize: '13px', color: '#94a3b8', marginTop: '2px' }}>
                    {chain.icon} {chain.name} {addressInput && `· ${addressInput.slice(0, 6)}...${addressInput.slice(-4)}`}
                  </div>
                  {tokenInfo?.found && (
                    <div className="token-info-card">
                      <div className="token-info-row">
                        <div className="token-info-item">
                          <span className="token-info-label">Price</span>
                          <span className="token-info-value">
                            ${Number(tokenInfo.priceUsd || 0) < 0.01
                              ? Number(tokenInfo.priceUsd || 0).toExponential(2)
                              : Number(tokenInfo.priceUsd || 0).toLocaleString(undefined, { maximumFractionDigits: 4 })}
                          </span>
                        </div>
                        <div className="token-info-item">
                          <span className="token-info-label">24h</span>
                          <span className={`token-info-value ${(tokenInfo.priceChange24h || 0) >= 0 ? 'positive' : 'negative'}`}>
                            {(tokenInfo.priceChange24h || 0) >= 0 ? '+' : ''}{tokenInfo.priceChange24h?.toFixed(2)}%
                          </span>
                        </div>
                        <div className="token-info-item">
                          <span className="token-info-label">Volume</span>
                          <span className="token-info-value">${(tokenInfo.volume24h || 0) >= 1e6
                            ? (tokenInfo.volume24h! / 1e6).toFixed(1) + 'M'
                            : (tokenInfo.volume24h || 0) >= 1e3
                              ? (tokenInfo.volume24h! / 1e3).toFixed(1) + 'K'
                              : tokenInfo.volume24h?.toFixed(0)}</span>
                        </div>
                        <div className="token-info-item">
                          <span className="token-info-label">Txns</span>
                          <span className="token-info-value">
                            {(tokenInfo.txns24h || 0).toLocaleString()}
                            <span style={{ fontSize: '10px', color: '#94a3b8', marginLeft: '4px' }}>
                              ({tokenInfo.buys24h}B / {tokenInfo.sells24h}S)
                            </span>
                          </span>
                        </div>
                      </div>
                      <div className="token-info-row">
                        <div className="token-info-item">
                          <span className="token-info-label">Liquidity</span>
                          <span className="token-info-value">${(tokenInfo.liquidity || 0) >= 1e6
                            ? (tokenInfo.liquidity! / 1e6).toFixed(1) + 'M'
                            : (tokenInfo.liquidity || 0) >= 1e3
                              ? (tokenInfo.liquidity! / 1e3).toFixed(1) + 'K'
                              : tokenInfo.liquidity?.toFixed(0)}</span>
                        </div>
                        <div className="token-info-item">
                          <span className="token-info-label">MCap</span>
                          <span className="token-info-value">{tokenInfo.marketCap
                            ? '$' + (tokenInfo.marketCap >= 1e9
                              ? (tokenInfo.marketCap / 1e9).toFixed(2) + 'B'
                              : tokenInfo.marketCap >= 1e6
                                ? (tokenInfo.marketCap / 1e6).toFixed(1) + 'M'
                                : (tokenInfo.marketCap / 1e3).toFixed(1) + 'K')
                            : '—'}</span>
                        </div>
                        <div className="token-info-item">
                          <span className="token-info-label">DEX</span>
                          <span className="token-info-value">{tokenInfo.dexName}</span>
                        </div>
                        <div className="token-info-item">
                          <span className="token-info-label">Pairs</span>
                          <span className="token-info-value">{tokenInfo.pairCount}</span>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
                {report && (
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <button className="code-action-btn" style={{ width: 'auto', padding: '6px 14px', fontSize: '13px', fontWeight: 500 }}
                      onClick={() => setShowReport(!showReport)}>
                      {showReport ? 'Pipeline' : 'Report'}
                    </button>
                    <button className="submit-btn" onClick={handleDownloadReport}>
                      Download Report ↓
                    </button>
                  </div>
                )}
              </div>

              {/* Progress bar */}
              <div className="progress-bar-container">
                <div className="progress-bar" style={{ width: `${progressPercent}%` }} />
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: '#94a3b8', marginBottom: '24px' }}>
                <span>{auditProgress}/{DEFAULT_AGENTS.length} agents</span>
                <span>{progressPercent}%</span>
              </div>

              {/* ─── Report View ─── */}
              {showReport && report && (
                <div className="audit-document">
                  {/* ─── Document Header ─── */}
                  <div className="doc-header">
                    <div className="doc-header-rule" />
                    <h1 className="doc-title">Security Audit Report</h1>
                    <table className="doc-meta-table">
                      <tbody>
                        <tr><td className="doc-meta-key">Contract</td><td>{report.contractName}</td></tr>
                        <tr><td className="doc-meta-key">Chain</td><td>{report.chain}</td></tr>
                        <tr><td className="doc-meta-key">Date</td><td>{new Date(report.timestamp).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</td></tr>
                        <tr><td className="doc-meta-key">Security Score</td><td>{report.riskScore} / 100 — {report.riskScore >= 80 ? 'Low Risk' : report.riskScore >= 50 ? 'Medium Risk' : 'High Risk'}</td></tr>
                        <tr><td className="doc-meta-key">Rules Applied</td><td>{report.rulesApplied}</td></tr>
                        <tr><td className="doc-meta-key">Findings</td><td>
                          {report.findings.filter(f => f.severity === 'critical').length} Critical · {report.findings.filter(f => f.severity === 'high').length} High · {report.findings.filter(f => f.severity === 'medium').length} Medium · {report.findings.filter(f => f.severity === 'low').length} Low
                        </td></tr>
                      </tbody>
                    </table>
                    <div className="doc-header-rule" />
                  </div>

                  {/* ─── 1.0 Executive Summary ─── */}
                  <section className="doc-section">
                    <h2 className="doc-section-num">1.0 — Executive Summary</h2>

                    {report.tokenOverview && (
                      <>
                        <h3 className="doc-subsection-title" style={{ marginBottom: '4px' }}>Contract Overview</h3>
                        <p className="doc-body">{report.tokenOverview}</p>
                      </>
                    )}

                    <h3 className="doc-subsection-title" style={{ marginTop: report.tokenOverview ? '16px' : '0', marginBottom: '4px' }}>Audit Summary</h3>
                    <p className="doc-body">{report.summary}</p>
                  </section>

                  {/* ─── 2.0 Methodology ─── */}
                  {report.methodology && (
                    <section className="doc-section">
                      <h2 className="doc-section-num">2.0 — Methodology</h2>
                      <p className="doc-body">{report.methodology}</p>
                      <p className="doc-body" style={{ marginTop: '8px' }}>
                        The following specialized agents were deployed against the contract:
                      </p>
                      <table className="doc-agent-table">
                        <thead>
                          <tr><th>Agent</th><th>Specialty</th><th>Result</th></tr>
                        </thead>
                        <tbody>
                          {report.agentResults.map((ar) => (
                            <tr key={ar.agentId}>
                              <td>{ar.agentName}</td>
                              <td>{DEFAULT_AGENTS.find(a => a.id === ar.agentId)?.description || '—'}</td>
                              <td>{ar.findingCount > 0 ? `${ar.findingCount} finding${ar.findingCount > 1 ? 's' : ''}` : 'Clear'}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </section>
                  )}

                  {/* ─── 3.0 Code Review ─── */}
                  {report.codeSegments && report.codeSegments.length > 0 && (
                    <section className="doc-section">
                      <h2 className="doc-section-num">3.0 — Code Review</h2>
                      <p className="doc-body">
                        The contract was decomposed into {report.codeSegments.length} logical segments for line-by-line analysis. Each segment is presented below with its source code, a technical assessment, and any associated findings.
                      </p>

                      {report.codeSegments.map((seg, i) => {
                        const segFindings = report.findings.filter(f =>
                          f.line && f.line >= seg.startLine && f.line <= seg.endLine
                        );
                        return (
                          <div key={i} className="doc-code-block">
                            <h3 className="doc-subsection-num">
                              3.{i + 1} — {seg.title}
                              <span className="doc-line-ref">Lines {seg.startLine}–{seg.endLine}</span>
                              <span className={`doc-risk-tag ${seg.risk}`}>{seg.risk}</span>
                            </h3>

                            <pre className="doc-code"><code>{seg.code}</code></pre>

                            <div className="doc-analysis">
                              <div className="doc-analysis-label">Analysis</div>
                              <p>{seg.summary}</p>
                            </div>

                            {segFindings.length > 0 && (
                              <div className="doc-seg-findings">
                                {segFindings.map((f, fi) => (
                                  <div key={fi} className="doc-seg-finding">
                                    <span className={`doc-sev ${f.severity}`}>{f.severity}</span>
                                    <strong>{f.title}</strong>
                                    {f.line && <span className="doc-finding-line">Line {f.line}</span>}
                                    <span className="doc-sep">—</span>
                                    <span>{f.description}</span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        );
                      })}
                    </section>
                  )}

                  {/* ─── 4.0 Detailed Findings ─── */}
                  <section className="doc-section">
                    <h2 className="doc-section-num">{report.codeSegments?.length ? '4.0' : '3.0'} — Findings</h2>
                    {report.findings.length === 0 ? (
                      <p className="doc-body">No vulnerabilities were identified during the audit. All 8 agents completed their scans without detecting issues within their respective domains.</p>
                    ) : (
                      <>
                        <p className="doc-body">
                          A total of {report.findings.length} finding{report.findings.length > 1 ? 's were' : ' was'} identified across {report.agentResults.filter(a => a.findingCount > 0).length} agent{report.agentResults.filter(a => a.findingCount > 0).length > 1 ? 's' : ''}.
                        </p>
                        {report.findings.map((f, i) => {
                          // Extract code snippet around the finding's line
                          const codeLines = code.split('\n');
                          const snippetRadius = 7;
                          const fLine = f.line || 0;
                          const snippetStart = Math.max(0, fLine - snippetRadius - 1);
                          const snippetEnd = Math.min(codeLines.length, fLine + snippetRadius);
                          const snippet = fLine > 0 ? codeLines.slice(snippetStart, snippetEnd) : [];

                          return (
                          <div key={i} className="doc-finding">
                            <h3 className="doc-finding-header">
                              <span className={`doc-sev ${f.severity}`}>{f.severity}</span>
                              <span className="doc-finding-title">{f.title}</span>
                              {f.line && <span className="doc-finding-line">Line {f.line}</span>}
                            </h3>
                            <div className="doc-finding-meta">
                              Identified by: {DEFAULT_AGENTS.find(a => a.id === f.agent)?.name || f.agent}
                            </div>
                            <p className="doc-body">{f.description}</p>

                            {/* Code snippet */}
                            {snippet.length > 0 && (
                              <div className="doc-finding-code-wrap">
                                <div className="doc-finding-code-label">
                                  Referenced Code — Lines {snippetStart + 1}–{snippetEnd}
                                </div>
                                <pre className="doc-finding-code">{snippet.map((line, li) => {
                                  const lineNum = snippetStart + li + 1;
                                  const isTarget = lineNum === fLine;
                                  return (
                                    <div key={li} className={`doc-code-line ${isTarget ? 'highlighted' : ''}`}>
                                      <span className="doc-code-linenum">{lineNum}</span>
                                      <span className="doc-code-text">{line}</span>
                                    </div>
                                  );
                                })}</pre>
                              </div>
                            )}

                            {/* Proof-of-Concept Exploit */}
                            {f.exploit && (
                              <div className="doc-exploit-wrap">
                                <div className="doc-exploit-label">⚔ Proof-of-Concept Exploit</div>
                                <pre className="doc-exploit-code"><code>{f.exploit}</code></pre>
                              </div>
                            )}

                            {/* Reproduction Steps */}
                            {f.reproductionSteps && f.reproductionSteps.length > 0 && (
                              <div className="doc-repro-wrap">
                                <div className="doc-repro-label">Attack Reproduction Steps</div>
                                <ol className="doc-repro-list">
                                  {f.reproductionSteps.map((step, si) => (
                                    <li key={si}>{step.replace(/^\d+\.\s*/, '')}</li>
                                  ))}
                                </ol>
                              </div>
                            )}

                            {f.recommendation && (
                              <div className="doc-recommendation">
                                <strong>Recommendation:</strong> {f.recommendation}
                              </div>
                            )}
                          </div>
                          );
                        })}
                      </>
                    )}
                  </section>

                  {/* ─── 5.0 Conclusion ─── */}
                  <section className="doc-section">
                    <h2 className="doc-section-num">{report.codeSegments?.length ? '5.0' : '4.0'} — Conclusion & Recommendation</h2>
                    <p className="doc-body">{report.recommendation}</p>
                  </section>

                  {/* ─── Footer ─── */}
                  <div className="doc-footer">
                    <div className="doc-header-rule" />
                    <p>Generated by <strong>Pentagonal</strong> — Smart Contract Forge</p>
                    <p>{new Date(report.timestamp).toLocaleString()}</p>
                  </div>
                </div>
              )}

              {/* ─── Pipeline View ─── */}
              {!showReport && (
                <>
                  {/* Agent Pipeline */}
                  <div className="agent-pipeline">
                    {agents.map((agent, idx) => (
                      <div key={agent.id} className={`pipeline-step ${agent.status}`}>
                        <div className="pipeline-indicator">
                          <div className={`pipeline-dot ${agent.status}`}>
                            {agent.status === 'clear' && '✓'}
                            {agent.status === 'finding' && '⚠'}
                            {agent.status === 'critical' && '!'}
                            {agent.status === 'scanning' && ''}
                            {agent.status === 'queued' && (idx + 1)}
                          </div>
                          {idx < agents.length - 1 && (
                            <div className={`pipeline-line ${
                              agent.status === 'clear' || agent.status === 'finding' || agent.status === 'critical' ? 'done' : ''
                            }`} />
                          )}
                        </div>
                        <div className="pipeline-content">
                          <div className="pipeline-name">{agent.name}</div>
                          <div className="pipeline-desc">{agent.description}</div>
                          <div className="pipeline-status-text">
                            {agent.status === 'queued' && 'Queued'}
                            {agent.status === 'scanning' && (
                              <span style={{ color: '#6366f1' }}>
                                <span className="code-status-dot" style={{ display: 'inline-block', width: '6px', height: '6px', borderRadius: '50%', background: '#6366f1', marginRight: '6px' }} />
                                Scanning...
                              </span>
                            )}
                            {agent.status === 'clear' && <span style={{ color: '#10b981' }}>✓ Clear</span>}
                            {agent.status === 'finding' && (
                              <span style={{ color: '#f59e0b' }}>⚠ {agent.findingCount} finding{agent.findingCount > 1 ? 's' : ''}</span>
                            )}
                            {agent.status === 'critical' && (
                              <span style={{ color: '#ef4444' }}>⛔ {agent.findingCount} finding{agent.findingCount > 1 ? 's' : ''}</span>
                            )}
                          </div>

                          {/* Technique list — visible when scanning or completed */}
                          {(agent.status === 'scanning' || agent.status === 'clear' || agent.status === 'finding' || agent.status === 'critical') && (
                            <div className={`pipeline-techniques ${agent.status === 'scanning' ? 'active' : ''}`}>
                              {agent.techniques.map((t, ti) => (
                                <div key={ti} className={`pipeline-technique ${
                                  agent.status === 'scanning' ? 'scanning' : 
                                  agent.status === 'clear' ? 'clear' : 'flagged'
                                }`}>
                                  <span className="technique-bullet">→</span>
                                  {t}
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Findings */}
                  {findings.length > 0 && (
                    <div className="findings-section" style={{ marginTop: '32px' }}>
                      <div className="findings-label">
                        {findings.filter(f => !f.fixed).length} Finding{findings.filter(f => !f.fixed).length !== 1 ? 's' : ''}
                      </div>
                      {findings.map((finding) => (
                        <div key={finding.id} className={`finding-card ${finding.severity === 'critical' ? 'critical' : ''}`}
                          style={finding.fixed ? { opacity: 0.5 } : {}}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                            <span className={`finding-severity ${finding.severity}`}>{finding.severity}</span>
                            <span style={{ fontSize: '12px', color: '#94a3b8' }}>
                              {DEFAULT_AGENTS.find(a => a.id === finding.agent)?.name || finding.agent}
                            </span>
                          </div>
                          <div className="finding-title">
                            {finding.fixed ? '✓ ' : ''}{finding.title}
                          </div>
                          <div className="finding-description">{finding.description}</div>
                          {finding.recommendation && (
                            <div style={{ fontSize: '13px', color: '#6366f1', marginBottom: '12px' }}>
                              💡 {finding.recommendation}
                            </div>
                          )}
                          {!finding.fixed && (
                            <div className="finding-actions">
                              <button className="finding-btn fix" onClick={() => handleFix(finding)}>Auto-Fix</button>
                              <button className="finding-btn ask"
                                onClick={() => setPrompt(`Tell me more about: ${finding.title}`)}>
                                Ask About This
                              </button>
                            </div>
                          )}
                        </div>
                      ))}

                      {/* Re-audit button after fixes */}
                      {findings.some(f => f.fixed) && (
                        <button className="submit-btn" style={{ marginTop: '16px' }}
                          onClick={() => startAudit()}>
                          Re-Audit Fixed Contract →
                        </button>
                      )}
                    </div>
                  )}
                </>
              )}

              {/* Q&A */}
              {qaAnswer && (
                <div className="user-prompt-card" style={{ borderLeft: '3px solid #6366f1', marginTop: '24px' }}>
                  <div className="user-prompt-label">ANSWER</div>
                  <div style={{ whiteSpace: 'pre-wrap', fontSize: '14px', lineHeight: '1.6' }}>{qaAnswer}</div>
                </div>
              )}

              <div style={{ height: '120px' }} />
            </div>
          )}
        </div>

        {/* ─── Bottom Prompt ─── */}
        {isActive && (
          <div className="bottom-prompt">
            <div className="prompt-container">
              <div className="prompt-box">
                <textarea
                  ref={textareaRef}
                  className="prompt-textarea"
                  placeholder={
                    isStreaming ? 'Generating...' :
                    isAuditing ? 'Auditing...' :
                    isScopeLoading ? 'Thinking...' :
                    isScopingView ? 'Type your answer...' :
                    isAuditView ? 'Ask about findings or request changes...' :
                    'Ask about this code or request changes...'
                  }
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  onKeyDown={handleKeyDown}
                  disabled={isStreaming || isAuditing || isScopeLoading}
                  rows={1}
                  style={{ minHeight: '44px' }}
                />
                <div className="prompt-controls">
                  <div className="prompt-tabs">
                    {!isAuditView && (
                      <>
                        <button className={`prompt-tab ${mode === 'create' ? 'active' : ''}`}
                          onClick={() => setMode('create')}>
                          ⚡ Create
                        </button>
                        <button className={`prompt-tab ${mode === 'audit' ? 'active' : ''}`}
                          onClick={() => { setMode('audit'); if (code && !isStreaming) startAudit(); }}>
                          🔍 Audit
                        </button>
                      </>
                    )}
                    <div style={{ position: 'relative' }}>
                      <button className="chain-selector"
                        onClick={() => setShowChainDropdown(!showChainDropdown)}>
                        <span>{chain.icon}</span>
                        <span>{chain.name}</span>
                      </button>
                    </div>
                  </div>
                  <div className="prompt-right">
                    <button className="submit-btn"
                      onClick={handleSubmit}
                      disabled={isStreaming || isAuditing || !prompt.trim()}>
                      Send →
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </>
  );
}
